### ISSUE TITLE
Publish on Chrome Store

### ISSUE THREAD

**Issue by vaibhavhrt** [ssight/CodeText#1]
Looks good to me, I will publish it on chrome store whenever I find some free time.

**Comment by ssight** [comment]
@vaibhavhrt Thanks.

Once it's done, do you mind replying with the link so I can update the README?

**Comment by vaibhavhrt** [comment]
Submitted for review, with following warning. Sorry for the delay, slipped my mind

### Publishing will be delayed
Because of the following issue, your extension may require an in-depth review:
- Broad Host Permissions
Instead of requesting broad host permissions, consider using the activeTab permission, or specify the sites that your extension needs access to. Both options are more secure than allowing full access to an indeterminate number of sites, and they may help minimize review times.

The activeTab permission allows access to a tab in response to an explicit user gesture.

```JSON
{
...
"permissions": ["activeTab"]
}
```
If your extension only needs to run on certain sites, simply specify those sites in the extension manifest:

```JSON
{
...
"permissions": ["https://example.com/*"]
}
```

**Comment by ssight** [comment]
No problem, I guess we'll just have to wait. Did they give an ETA by any chance?

**Comment by vaibhavhrt** [comment]
I think it said about 7 days. When I used to publish extensions(about a year ago), it used to take 4-5 hours, but right they are saying it will take longer due to covid.

**Comment by ssight** [comment]
Ah, I see. Well at least it'll be on the Web Store eventually!

**Comment by vaibhavhrt** [comment]
Published https://chrome.google.com/webstore/detail/bgapacmlaofadjgmhfhoclmhbgljfnig/publish-accepted?authuser=0&hl=en

**Comment by ssight** [comment]
Cool! I'll update the README :)
